// <auto-generated />
using System;
using BookingWeb.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingWeb.Server.Migrations
{
    [DbContext(typeof(BookingBusContext))]
    partial class BookingBusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingWeb.Server.Models.Benxe", b =>
                {
                    b.Property<int>("IdBenXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_BenXe");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBenXe"));

                    b.Property<int>("IdTinhThanh")
                        .HasColumnType("int")
                        .HasColumnName("ID_TinhThanh");

                    b.Property<string>("TenBenXe")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdBenXe")
                        .HasName("PK__benxe__5D85FA844FDC4F24");

                    b.HasIndex("IdTinhThanh");

                    b.ToTable("benxe", (string)null);
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Chuyenxe", b =>
                {
                    b.Property<int>("IdChuyenXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ChuyenXe");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChuyenXe"));

                    b.Property<int>("IdTuyenDuong")
                        .HasColumnType("int")
                        .HasColumnName("ID_TuyenDuong");

                    b.Property<int>("IdXe")
                        .HasColumnType("int")
                        .HasColumnName("ID_Xe");

                    b.Property<string>("ThoiGianDen")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Thoi_GianDen")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ThoiGianKh")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Thoi_GianKH")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdChuyenXe")
                        .HasName("PK__chuyenxe__108DC34A90342C66");

                    b.HasIndex("IdTuyenDuong");

                    b.HasIndex("IdXe");

                    b.ToTable("chuyenxe", (string)null);
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Loaixe", b =>
                {
                    b.Property<int>("IdLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Loai");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLoai"));

                    b.Property<int?>("SoGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("So_Ghe")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("TenLoai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Ten_Loai")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdLoai")
                        .HasName("PK__loaixe__914C231484162537");

                    b.ToTable("loaixe", (string)null);
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Nguoidung", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_User");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("DiaChi")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Dia_Chi")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("HoTen")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ho_Ten")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int>("IdAccount")
                        .HasColumnType("int")
                        .HasColumnName("ID_Account");

                    b.Property<string>("Phone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdUser")
                        .HasName("PK__nguoidun__ED4DE442BDF9A79A");

                    b.HasIndex("IdAccount");

                    b.ToTable("nguoidung", (string)null);
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Phanquyen", b =>
                {
                    b.Property<int>("IdQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Quyen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuyen"));

                    b.Property<string>("TenQuyen")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdQuyen")
                        .HasName("PK__phanquye__D219AE521EF8DFDB");

                    b.ToTable("phanquyen", (string)null);
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Phieudat", b =>
                {
                    b.Property<int>("IdPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Phieu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPhieu"));

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("ID_User");

                    b.Property<DateOnly?>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("Ngay_Lap")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<decimal?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Tong_Tien")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdPhieu")
                        .HasName("PK__phieudat__E61CE97EEA5EA967");

                    b.HasIndex("IdUser");

                    b.ToTable("phieudat", (string)null);
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Taikhoan", b =>
                {
                    b.Property<int>("IdAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Account");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccount"));

                    b.Property<int>("IdQuyen")
                        .HasColumnType("int")
                        .HasColumnName("ID_Quyen");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdAccount")
                        .HasName("PK__taikhoan__213379EB2699579B");

                    b.HasIndex("IdQuyen");

                    b.ToTable("taikhoan", (string)null);
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Thanhtoan", b =>
                {
                    b.Property<int>("IdThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ThanhToan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThanhToan"));

                    b.Property<int>("IdPhieuDat")
                        .HasColumnType("int")
                        .HasColumnName("ID_PhieuDat");

                    b.Property<string>("PhuongThucTt")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PhuongThuc_TT")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<decimal?>("SoTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("So_Tien")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdThanhToan")
                        .HasName("PK__thanhtoa__AB2E56314DA22CB2");

                    b.HasIndex("IdPhieuDat");

                    b.ToTable("thanhtoan", (string)null);
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Tinhthanh", b =>
                {
                    b.Property<int>("IdTinhThanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_TinhThanh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTinhThanh"));

                    b.Property<string>("TenTinhThanh")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Ten_TinhThanh")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdTinhThanh")
                        .HasName("PK__tinhthan__BC0EB70B648D8A7D");

                    b.ToTable("tinhthanh", (string)null);
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Tuyenduong", b =>
                {
                    b.Property<int>("IdTuyenDuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_TuyenDuong");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTuyenDuong"));

                    b.Property<decimal?>("GiaVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Gia_Ve")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<decimal?>("KhoangCach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Khoang_Cach")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int>("NoiDen")
                        .HasColumnType("int")
                        .HasColumnName("Noi_Den");

                    b.Property<int>("NoiKhoiHanh")
                        .HasColumnType("int")
                        .HasColumnName("Noi_KhoiHanh");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdTuyenDuong")
                        .HasName("PK__tuyenduo__8D9665CDB5016B03");

                    b.HasIndex("NoiDen");

                    b.HasIndex("NoiKhoiHanh");

                    b.ToTable("tuyenduong", (string)null);
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Vexe", b =>
                {
                    b.Property<int>("IdVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Ve");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVe"));

                    b.Property<int>("IdChuyenXe")
                        .HasColumnType("int")
                        .HasColumnName("ID_ChuyenXe");

                    b.Property<int?>("IdPhieu")
                        .HasColumnType("int")
                        .HasColumnName("ID_Phieu");

                    b.Property<DateOnly>("NgayKhoiHanh")
                        .HasColumnType("date");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("ViTriGhe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVe")
                        .HasName("PK__vexe__8B63A19CBA40D288");

                    b.HasIndex("IdChuyenXe");

                    b.HasIndex("IdPhieu");

                    b.ToTable("vexe", (string)null);
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Xe", b =>
                {
                    b.Property<int>("IdXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Xe");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdXe"));

                    b.Property<string>("BienSo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Bien_So")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int>("IdLoai")
                        .HasColumnType("int")
                        .HasColumnName("ID_Loai");

                    b.Property<bool>("TinhTrang")
                        .HasColumnType("bit")
                        .HasColumnName("Tinh_Trang");

                    b.HasKey("IdXe")
                        .HasName("PK__xe__8B62515E52C40997");

                    b.HasIndex("IdLoai");

                    b.ToTable("xe", (string)null);
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Benxe", b =>
                {
                    b.HasOne("BookingWeb.Server.Models.Tinhthanh", "IdTinhThanhNavigation")
                        .WithMany("Benxes")
                        .HasForeignKey("IdTinhThanh")
                        .IsRequired()
                        .HasConstraintName("FK_benxe_tinhthanh");

                    b.Navigation("IdTinhThanhNavigation");
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Chuyenxe", b =>
                {
                    b.HasOne("BookingWeb.Server.Models.Tuyenduong", "IdTuyenDuongNavigation")
                        .WithMany("Chuyenxes")
                        .HasForeignKey("IdTuyenDuong")
                        .IsRequired()
                        .HasConstraintName("FK_chuyenxe_tuyenduong");

                    b.HasOne("BookingWeb.Server.Models.Xe", "IdXeNavigation")
                        .WithMany("Chuyenxes")
                        .HasForeignKey("IdXe")
                        .IsRequired()
                        .HasConstraintName("FK_chuyenxe_xe");

                    b.Navigation("IdTuyenDuongNavigation");

                    b.Navigation("IdXeNavigation");
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Nguoidung", b =>
                {
                    b.HasOne("BookingWeb.Server.Models.Taikhoan", "IdAccountNavigation")
                        .WithMany("Nguoidungs")
                        .HasForeignKey("IdAccount")
                        .IsRequired()
                        .HasConstraintName("FK_nguoidung_taikhoan");

                    b.Navigation("IdAccountNavigation");
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Phieudat", b =>
                {
                    b.HasOne("BookingWeb.Server.Models.Nguoidung", "IdUserNavigation")
                        .WithMany("Phieudats")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK_phieudat_nguoidung");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Taikhoan", b =>
                {
                    b.HasOne("BookingWeb.Server.Models.Phanquyen", "IdQuyenNavigation")
                        .WithMany("Taikhoans")
                        .HasForeignKey("IdQuyen")
                        .IsRequired()
                        .HasConstraintName("FK_taikhoan_phanquyen");

                    b.Navigation("IdQuyenNavigation");
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Thanhtoan", b =>
                {
                    b.HasOne("BookingWeb.Server.Models.Phieudat", "IdPhieuDatNavigation")
                        .WithMany("Thanhtoans")
                        .HasForeignKey("IdPhieuDat")
                        .IsRequired()
                        .HasConstraintName("FK_thanhtoan_phieudat");

                    b.Navigation("IdPhieuDatNavigation");
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Tuyenduong", b =>
                {
                    b.HasOne("BookingWeb.Server.Models.Benxe", "NoiDenNavigation")
                        .WithMany("TuyenduongNoiDenNavigations")
                        .HasForeignKey("NoiDen")
                        .IsRequired()
                        .HasConstraintName("FK_tuyenduong_benxe1");

                    b.HasOne("BookingWeb.Server.Models.Benxe", "NoiKhoiHanhNavigation")
                        .WithMany("TuyenduongNoiKhoiHanhNavigations")
                        .HasForeignKey("NoiKhoiHanh")
                        .IsRequired()
                        .HasConstraintName("FK_tuyenduong_benxe");

                    b.Navigation("NoiDenNavigation");

                    b.Navigation("NoiKhoiHanhNavigation");
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Vexe", b =>
                {
                    b.HasOne("BookingWeb.Server.Models.Chuyenxe", "IdChuyenXeNavigation")
                        .WithMany("Vexes")
                        .HasForeignKey("IdChuyenXe")
                        .IsRequired()
                        .HasConstraintName("FK_vexe_chuyenxe");

                    b.HasOne("BookingWeb.Server.Models.Phieudat", "IdPhieuNavigation")
                        .WithMany("Vexes")
                        .HasForeignKey("IdPhieu")
                        .HasConstraintName("FK_vexe_phieudat");

                    b.Navigation("IdChuyenXeNavigation");

                    b.Navigation("IdPhieuNavigation");
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Xe", b =>
                {
                    b.HasOne("BookingWeb.Server.Models.Loaixe", "IdLoaiNavigation")
                        .WithMany("Xes")
                        .HasForeignKey("IdLoai")
                        .IsRequired()
                        .HasConstraintName("FK_xe_loaixe");

                    b.Navigation("IdLoaiNavigation");
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Benxe", b =>
                {
                    b.Navigation("TuyenduongNoiDenNavigations");

                    b.Navigation("TuyenduongNoiKhoiHanhNavigations");
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Chuyenxe", b =>
                {
                    b.Navigation("Vexes");
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Loaixe", b =>
                {
                    b.Navigation("Xes");
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Nguoidung", b =>
                {
                    b.Navigation("Phieudats");
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Phanquyen", b =>
                {
                    b.Navigation("Taikhoans");
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Phieudat", b =>
                {
                    b.Navigation("Thanhtoans");

                    b.Navigation("Vexes");
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Taikhoan", b =>
                {
                    b.Navigation("Nguoidungs");
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Tinhthanh", b =>
                {
                    b.Navigation("Benxes");
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Tuyenduong", b =>
                {
                    b.Navigation("Chuyenxes");
                });

            modelBuilder.Entity("BookingWeb.Server.Models.Xe", b =>
                {
                    b.Navigation("Chuyenxes");
                });
#pragma warning restore 612, 618
        }
    }
}
